import React from 'react';
import {
    Box, Typography, Container, Button, Divider, useTheme,
} from '@mui/material';
import { ArrowBack, Security } from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';

const Section = ({ title, children }) => (
    <Box sx={{ mb: 4 }}>
        <Typography variant="h6" fontWeight={700} mb={1.5}>
            {title}
        </Typography>
        <Typography variant="body2" color="text.secondary" lineHeight={1.9}>
            {children}
        </Typography>
    </Box>
);

export default function PrivacyPolicy() {
    const theme = useTheme();
    const isDark = theme.palette.mode === 'dark';
    const accent = isDark ? '#AED6F1' : '#3AB0A9';
    const navigate = useNavigate();

    return (
        <Box sx={{ minHeight: '100vh', bgcolor: 'background.default', py: 8 }}>
            <Container maxWidth="md">
                <Button
                    startIcon={<ArrowBack />}
                    onClick={() => navigate('/')}
                    sx={{ mb: 4, color: accent, fontWeight: 600 }}
                >
                    Back to Home
                </Button>

                <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 1 }}>
                    <Security sx={{ fontSize: 36, color: accent }} />
                    <Typography variant="h4" fontWeight={900}>
                        Privacy Policy
                    </Typography>
                </Box>
                <Typography variant="body2" color="text.secondary" mb={4}>
                    Last updated: April 2026
                </Typography>

                <Divider sx={{ mb: 4 }} />

                <Section title="1. Overview">
                    MedViD ("the Platform") is an AI-assisted gastrointestinal endoscopy diagnostic
                    tool intended for use by licensed medical professionals. This Privacy Policy
                    explains what data we collect, how it is used, and how it is protected. By using
                    MedViD, you agree to the practices described in this policy.
                </Section>

                <Section title="2. Data We Collect">
                    We collect the following categories of information:{'\n\n'}
                    • <strong>Account data:</strong> Full name, email address, professional role,
                    designation, institutional affiliation, and phone number provided during
                    registration.{'\n\n'}
                    • <strong>Patient and clinical data:</strong> Endoscopy videos uploaded for
                    analysis, associated patient identifiers (name, age, gender), and diagnostic
                    results generated by the AI model.{'\n\n'}
                    • <strong>Usage and audit data:</strong> Actions performed on the platform
                    (uploads, analysis runs, consultant referrals, report exports) logged with
                    timestamps for clinical accountability.{'\n\n'}
                    • <strong>Technical data:</strong> Browser type, IP address, and session
                    information for security and platform integrity purposes.
                </Section>

                <Section title="3. How We Use Your Data">
                    Data collected is used solely to:{'\n\n'}
                    • Provide AI-assisted diagnostic analysis of endoscopy videos.{'\n\n'}
                    • Maintain patient records and associate them with diagnostic reports.{'\n\n'}
                    • Enable consultant collaboration and case referral workflows.{'\n\n'}
                    • Generate and export clinical reports in PDF format.{'\n\n'}
                    • Maintain a complete audit trail for clinical and regulatory accountability.{'\n\n'}
                    • Administer user accounts and enforce platform access controls.
                </Section>

                <Section title="4. Who Can Access Your Data">
                    • <strong>You (the user):</strong> Full access to your own uploaded cases,
                    patient records, and diagnostic reports.{'\n\n'}
                    • <strong>Consultants:</strong> Access only to cases explicitly referred to them
                    by the referring doctor.{'\n\n'}
                    • <strong>System administrators:</strong> Limited access for account management
                    and audit review. Administrators do not access clinical content unless required
                    for platform maintenance.{'\n\n'}
                    • <strong>Third parties:</strong> We do not sell, rent, or share any user or
                    patient data with third parties for marketing or commercial purposes.
                </Section>

                <Section title="5. Data Retention">
                    Account data is retained for the duration of your active account. Diagnostic
                    records and audit logs are retained as required by applicable clinical data
                    retention regulations. Upon account deletion, personal data is removed within
                    30 days except where retention is required by law.
                </Section>

                <Section title="6. Data Security">
                    All data is transmitted over encrypted HTTPS connections. Passwords are hashed
                    before storage and are never stored in plaintext. Access to the platform is
                    controlled via JWT-based authentication. Administrative access is further
                    restricted by separate credentials. We implement reasonable technical and
                    organisational measures to protect data against unauthorised access, loss,
                    or destruction.
                </Section>

                <Section title="7. Your Rights">
                    You have the right to request access to, correction of, or deletion of your
                    personal data. To make such a request, contact the platform administrator.
                    Requests will be processed within 30 days of receipt.
                </Section>

                <Section title="8. Changes to This Policy">
                    This policy may be updated from time to time. Continued use of MedViD after
                    changes are posted constitutes acceptance of the updated policy. Users will be
                    notified of material changes via email.
                </Section>

                <Section title="9. Contact">
                    For privacy-related questions or data requests, contact the MedViD system
                    administrator via the platform's administrative channel or through your
                    institutional point of contact.
                </Section>

                <Divider sx={{ mt: 2, mb: 4 }} />
                <Typography variant="caption" color="text.secondary">
                    © {new Date().getFullYear()} MedViD — AI-Assisted GI Endoscopy Diagnostics
                </Typography>
            </Container>
        </Box>
    );
}